[2025-02-11T15:45:13.507+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T15:45:13.517+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e2e_data_loading_to_pg_dag.load_final_table_task manual__2025-02-11T09:44:57.216284+00:00 [queued]>
[2025-02-11T15:45:13.527+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e2e_data_loading_to_pg_dag.load_final_table_task manual__2025-02-11T09:44:57.216284+00:00 [queued]>
[2025-02-11T15:45:13.527+0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T15:45:13.542+0600] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): load_final_table_task> on 2025-02-11 09:44:57.216284+00:00
[2025-02-11T15:45:13.552+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'e2e_data_loading_to_pg_dag', 'load_final_table_task', 'manual__2025-02-11T09:44:57.216284+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/e_to_e_processing.py', '--cfg-path', '/tmp/tmp4cd9qcse']
[2025-02-11T15:45:13.554+0600] {standard_task_runner.py:105} INFO - Job 35: Subtask load_final_table_task
[2025-02-11T15:45:13.558+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=96222) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-11T15:45:13.559+0600] {standard_task_runner.py:72} INFO - Started process 96243 to run task
[2025-02-11T15:45:13.596+0600] {task_command.py:467} INFO - Running <TaskInstance: e2e_data_loading_to_pg_dag.load_final_table_task manual__2025-02-11T09:44:57.216284+00:00 [running]> on host shamim-X541UV
[2025-02-11T15:45:13.740+0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='e2e_data_loading_to_pg_dag' AIRFLOW_CTX_TASK_ID='load_final_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T09:44:57.216284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T09:44:57.216284+00:00'
[2025-02-11T15:45:13.743+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-11T15:45:13.743+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-11T15:45:13.744+0600] {logging_mixin.py:190} INFO - Current task name:load_final_table_task state:running start_date:2025-02-11 09:45:13.517920+00:00
[2025-02-11T15:45:13.745+0600] {logging_mixin.py:190} INFO - Dag name:e2e_data_loading_to_pg_dag and current dag run status:running
[2025-02-11T15:45:13.745+0600] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T15:45:13.746+0600] {sql.py:295} INFO - Executing: 
    CREATE TABLE fact_table (
	"name" varchar(100) NULL,
	salary numeric(10, 2) NULL
);


CREATE OR REPLACE PROCEDURE transform_and_load_data()
LANGUAGE plpgsql
AS $procedure$
BEGIN
    -- Aggregate data from the staging_table
    INSERT INTO fact_table (name, salary)
    SELECT name, SUM(salary)
    FROM staging_table
    GROUP BY name;

END;
$procedure$
    CALL transform_and_load_data(); 
    
[2025-02-11T15:45:13.755+0600] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-02-11T15:45:13.765+0600] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-02-11T15:45:13.785+0600] {sql.py:511} INFO - Running statement: 
    CREATE TABLE fact_table (
	"name" varchar(100) NULL,
	salary numeric(10, 2) NULL
);


CREATE OR REPLACE PROCEDURE transform_and_load_data()
LANGUAGE plpgsql
AS $procedure$
BEGIN
    -- Aggregate data from the staging_table
    INSERT INTO fact_table (name, salary)
    SELECT name, SUM(salary)
    FROM staging_table
    GROUP BY name;

END;
$procedure$
    CALL transform_and_load_data(); 
    , parameters: None
[2025-02-11T15:45:13.787+0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "CALL"
LINE 20:     CALL transform_and_load_data(); 
             ^

[2025-02-11T15:45:13.794+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-11T15:45:13.794+0600] {logging_mixin.py:190} INFO - Task start:2025-02-11 09:45:13.517920+00:00 end:2025-02-11 09:45:13.793677+00:00 duration:0.275757
[2025-02-11T15:45:13.795+0600] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): load_final_table_task> dag:<DAG: e2e_data_loading_to_pg_dag> dagrun:<DagRun e2e_data_loading_to_pg_dag @ 2025-02-11 09:44:57.216284+00:00: manual__2025-02-11T09:44:57.216284+00:00, state:running, queued_at: 2025-02-11 09:44:57.247147+00:00. externally triggered: True>
[2025-02-11T15:45:13.795+0600] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "CALL"
LINE 20:     CALL transform_and_load_data(); 
             ^
[2025-02-11T15:45:13.795+0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=e2e_data_loading_to_pg_dag, task_id=load_final_table_task, run_id=manual__2025-02-11T09:44:57.216284+00:00, execution_date=20250211T094457, start_date=20250211T094513, end_date=20250211T094513
[2025-02-11T15:45:13.809+0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T15:45:13.810+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task load_final_table_task (syntax error at or near "CALL"
LINE 20:     CALL transform_and_load_data(); 
             ^
; 96243)
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "CALL"
LINE 20:     CALL transform_and_load_data(); 
             ^

[2025-02-11T15:45:13.856+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-11T15:45:13.871+0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T15:45:13.872+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
