[2025-02-11T13:52:48.365+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T13:52:48.378+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e2e_data_loading_to_pg_dag.create_table_task manual__2025-02-11T07:52:40.632360+00:00 [queued]>
[2025-02-11T13:52:48.386+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e2e_data_loading_to_pg_dag.create_table_task manual__2025-02-11T07:52:40.632360+00:00 [queued]>
[2025-02-11T13:52:48.386+0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T13:52:48.403+0600] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): create_table_task> on 2025-02-11 07:52:40.632360+00:00
[2025-02-11T13:52:48.415+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'e2e_data_loading_to_pg_dag', 'create_table_task', 'manual__2025-02-11T07:52:40.632360+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/e_to_e_processing.py', '--cfg-path', '/tmp/tmpek_gka5i']
[2025-02-11T13:52:48.416+0600] {standard_task_runner.py:105} INFO - Job 17: Subtask create_table_task
[2025-02-11T13:52:48.420+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=65980) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-11T13:52:48.421+0600] {standard_task_runner.py:72} INFO - Started process 66037 to run task
[2025-02-11T13:52:48.459+0600] {task_command.py:467} INFO - Running <TaskInstance: e2e_data_loading_to_pg_dag.create_table_task manual__2025-02-11T07:52:40.632360+00:00 [running]> on host shamim-X541UV
[2025-02-11T13:52:48.532+0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='e2e_data_loading_to_pg_dag' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T07:52:40.632360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T07:52:40.632360+00:00'
[2025-02-11T13:52:48.534+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-11T13:52:48.534+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-11T13:52:48.534+0600] {logging_mixin.py:190} INFO - Current task name:create_table_task state:running start_date:2025-02-11 07:52:48.379232+00:00
[2025-02-11T13:52:48.535+0600] {logging_mixin.py:190} INFO - Dag name:e2e_data_loading_to_pg_dag and current dag run status:running
[2025-02-11T13:52:48.535+0600] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T13:52:48.535+0600] {sql.py:295} INFO - Executing: 
    DROP TABLE IF EXISTS staging_table;
    CREATE TABLE IF NOT EXIST staging_table(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    month VARCHAR(100),
    slary NUMERIC
    );
    
[2025-02-11T13:52:48.543+0600] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-02-11T13:52:48.552+0600] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-02-11T13:52:48.578+0600] {sql.py:511} INFO - Running statement: 
    DROP TABLE IF EXISTS staging_table;
    CREATE TABLE IF NOT EXIST staging_table(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    month VARCHAR(100),
    slary NUMERIC
    );
    , parameters: None
[2025-02-11T13:52:48.581+0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "EXIST"
LINE 3:     CREATE TABLE IF NOT EXIST staging_table(
                                ^

[2025-02-11T13:52:48.592+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-11T13:52:48.593+0600] {logging_mixin.py:190} INFO - Task start:2025-02-11 07:52:48.379232+00:00 end:2025-02-11 07:52:48.592142+00:00 duration:0.21291
[2025-02-11T13:52:48.593+0600] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): create_table_task> dag:<DAG: e2e_data_loading_to_pg_dag> dagrun:<DagRun e2e_data_loading_to_pg_dag @ 2025-02-11 07:52:40.632360+00:00: manual__2025-02-11T07:52:40.632360+00:00, state:running, queued_at: 2025-02-11 07:52:40.707589+00:00. externally triggered: True>
[2025-02-11T13:52:48.593+0600] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "EXIST"
LINE 3:     CREATE TABLE IF NOT EXIST staging_table(
                                ^
[2025-02-11T13:52:48.594+0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=e2e_data_loading_to_pg_dag, task_id=create_table_task, run_id=manual__2025-02-11T07:52:40.632360+00:00, execution_date=20250211T075240, start_date=20250211T075248, end_date=20250211T075248
[2025-02-11T13:52:48.606+0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T13:52:48.607+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task create_table_task (syntax error at or near "EXIST"
LINE 3:     CREATE TABLE IF NOT EXIST staging_table(
                                ^
; 66037)
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "EXIST"
LINE 3:     CREATE TABLE IF NOT EXIST staging_table(
                                ^

[2025-02-11T13:52:48.636+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-11T13:52:48.659+0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T13:52:48.667+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
