[2025-02-11T13:53:48.329+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T13:53:48.341+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e2e_data_loading_to_pg_dag.load_df_task manual__2025-02-11T07:53:36.177603+00:00 [queued]>
[2025-02-11T13:53:48.348+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e2e_data_loading_to_pg_dag.load_df_task manual__2025-02-11T07:53:36.177603+00:00 [queued]>
[2025-02-11T13:53:48.349+0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T13:53:48.363+0600] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_df_task> on 2025-02-11 07:53:36.177603+00:00
[2025-02-11T13:53:48.376+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'e2e_data_loading_to_pg_dag', 'load_df_task', 'manual__2025-02-11T07:53:36.177603+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/e_to_e_processing.py', '--cfg-path', '/tmp/tmphjlg8lup']
[2025-02-11T13:53:48.378+0600] {standard_task_runner.py:105} INFO - Job 19: Subtask load_df_task
[2025-02-11T13:53:48.385+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=66303) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-11T13:53:48.386+0600] {standard_task_runner.py:72} INFO - Started process 66316 to run task
[2025-02-11T13:53:48.427+0600] {task_command.py:467} INFO - Running <TaskInstance: e2e_data_loading_to_pg_dag.load_df_task manual__2025-02-11T07:53:36.177603+00:00 [running]> on host shamim-X541UV
[2025-02-11T13:53:48.550+0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='e2e_data_loading_to_pg_dag' AIRFLOW_CTX_TASK_ID='load_df_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T07:53:36.177603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T07:53:36.177603+00:00'
[2025-02-11T13:53:48.552+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-11T13:53:48.552+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-11T13:53:48.553+0600] {logging_mixin.py:190} INFO - Current task name:load_df_task state:running start_date:2025-02-11 07:53:48.342063+00:00
[2025-02-11T13:53:48.553+0600] {logging_mixin.py:190} INFO - Dag name:e2e_data_loading_to_pg_dag and current dag run status:running
[2025-02-11T13:53:48.553+0600] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T13:53:48.554+0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/dags/e_to_e_processing.py", line 57, in insert_df_into_pg
    tuples=[tuple(x) for x in df.to.numpy()]
                              ^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'to'
[2025-02-11T13:53:48.567+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-11T13:53:48.568+0600] {logging_mixin.py:190} INFO - Task start:2025-02-11 07:53:48.342063+00:00 end:2025-02-11 07:53:48.566993+00:00 duration:0.22493
[2025-02-11T13:53:48.569+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_df_task> dag:<DAG: e2e_data_loading_to_pg_dag> dagrun:<DagRun e2e_data_loading_to_pg_dag @ 2025-02-11 07:53:36.177603+00:00: manual__2025-02-11T07:53:36.177603+00:00, state:running, queued_at: 2025-02-11 07:53:36.273942+00:00. externally triggered: True>
[2025-02-11T13:53:48.570+0600] {logging_mixin.py:190} INFO - Failure caused by 'DataFrame' object has no attribute 'to'
[2025-02-11T13:53:48.570+0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=e2e_data_loading_to_pg_dag, task_id=load_df_task, run_id=manual__2025-02-11T07:53:36.177603+00:00, execution_date=20250211T075336, start_date=20250211T075348, end_date=20250211T075348
[2025-02-11T13:53:48.586+0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T13:53:48.587+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task load_df_task ('DataFrame' object has no attribute 'to'; 66316)
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/dags/e_to_e_processing.py", line 57, in insert_df_into_pg
    tuples=[tuple(x) for x in df.to.numpy()]
                              ^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'to'
[2025-02-11T13:53:48.641+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-11T13:53:48.656+0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T13:53:48.656+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
